### ISSUE TITLE
Make Strip View Widget for corporate site.

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#1388] opened 2018-09-21 09:35 UTC
We need to have a strip view widget for different ETOs. 
First, one to come will be our own strip view, second will be Founders Bank.

<img width="640" alt="screen shot 2018-09-20 at 17 14 10" src="https://user-images.githubusercontent.com/2290474/45828361-a327b580-bcf8-11e8-9eb3-7276932202b5.png">

This will be placed on our  corporate website neufund.org 
and on the website of our partner: Founders Bank and Maltese Stock Exchange.  
So we need to design iFrame

**Comment by desfero** [comment] 2018-10-01 18:57
Duplicate of https://github.com/Neufund/platform-frontend/issues/1271?

**Comment by SergejSoft** [comment] 2018-10-16 14:19
@falinebambi we need to have fixed with and hights for the iframe. Now all widgets have a different site.

**Comment by falinebambi** [comment] 2018-10-23 09:43
Link paths: 
Click CTA button and user not logged in goes to register page on platform 
Click CTA button and user logged in goes to listing page on platform
User clicks anywhere else on widget and goes to public listing page 

Slack me if you have any questions

**Comment by falinebambi** [comment] 2018-10-24 12:04
No personal data of login state is carried through in the widget
CTA always shows Invest Now
but you can not invest directly through the widget
it directs you to the platform 
(click "invest now" on the widget and then click "invest now" second time on the widget on public listing page)
the wording invest now on the external widget is there because it has higher marketing traction

**Comment by banciur** [comment] 2018-11-13 16:13
Done but PR was not connected to issue

**Closed by banciur** 2018-11-13 16:13 UTC
Labels: Design
