### ISSUE TITLE
Investment flow - masked input strips a dot at end of input

### ISSUE THREAD

**Issue by drakkein** [Neufund/platform-frontend#2688] opened 2019-04-02 09:06 UTC
**Description**
Masked input strips a dot at end of input. If you write down a number and then you add dot in a middle it will work correctly.

**Environment**

**Steps To Reproduce**

**Actual behaviour**
Should not strip dot at any position. 

**Expected behavior**

**Comments, context, logs**
It is stripped by value conversions inside sagas. 
```
        yield put(actions.investmentFlow.setEthValue(ethVal.toFixed(0, BigNumber.ROUND_UP)));
        yield put(actions.investmentFlow.setEurValue(bignumber.toFixed(0, BigNumber.ROUND_UP)));
```

**Screenshots**

**Comment by AlexeyTuboltsev** [comment] 2019-04-09 08:57
a duplicate of and will be sold with #2687

**Closed by AlexeyTuboltsev** 2019-04-09 08:57 UTC
