### ISSUE TITLE
TEST on staging

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#1863] opened 2018-11-19 12:26 UTC
If the user enters an Adress not associated with ICBM we get loading page and error on the right. 

What we need: Display a text in the box.

"We could not find this address in the list of ICBM investors"

<img width="1440" alt="screen shot 2018-11-19 at 13 19 41" src="https://user-images.githubusercontent.com/2290474/48706909-02714b80-ebfe-11e8-9d69-bdf4c96ae9c2.png">

**Comment by banciur** [comment] 2018-11-19 14:42
For ICBM wallet popup works correctly.

Screen shown above can be observed when there is no ICBM wallet for given address. It's not a bug per se but missing feature.
What is happening we show spinner during loading of wallet. When wallet is not recognized we throw error (my suspicion) that is displayed on top right screen in red rectangle. We should handle this case, hide spinner and show  message that under address there is no ICBM wallet.

Although there is another thing to change there. We need to reset popup state on beginning of every check.
steps to observe:
1 use ICBM wallet and see filled out popup
2 close it
3 use non ICBM wallet. 
Pop up that will open with previous state of ICBM wallet.

**Comment by glupiawymowka** [comment] 2018-11-19 23:05
Please put in the red error bar:
"We were unable to find an ICBM wallet for the entered address."

**Comment by Moejoe90** [comment] 2018-11-20 09:59
@SergejSoft @glupiawymowka 
There is a conflict between texts which text should come
"We were unable to find an ICBM wallet for the entered address."
or
"We could not find this address in the list of ICBM investors"

**Closed** 2018-11-26 13:02 UTC
