### ISSUE TITLE
incorrect signer show for split second for a light wallet

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-frontend#3901] opened 2020-01-14 13:26 UTC
**Description**
When any transaction is signed via light wallet, after providing password and signing a stock signer window is shown.

**Environment**
Any

**Steps To Reproduce**
Sign a transaction and try to throttle network connection down. I do not guarantee you going to see this but you are able for sure able to find in the code why we have it.

**Actual behaviour**
See screnshot

**Expected behavior**
We do not show this "modal" in case of light wallet. Alternatively we can change the texting but I'd prefer the first one

**Screenshots**
![image](https://user-images.githubusercontent.com/17202864/72348075-d8b89500-36d9-11ea-82d3-95c5266212a9.png)

**Comment by desfero** [comment] 2020-01-14 13:44
Closing as it's a duplicate of #2658

**Closed by desfero** 2020-01-14 13:45 UTC
Labels: Bug
