### ISSUE TITLE
Enable EU-SME ETO in Issuer forms

### ISSUE THREAD

**Issue by Vanilizer** [Neufund/platform-frontend#3363] opened 2019-08-26 10:45 UTC
**Background**
Since the EU-SME ETO is now legal live - raise up to 20M - we should enable it in the ETO Terms Form. I remember it is done, just hidden. Please enable it.

**Designs**
not needed.

**Acceptance criteria**
If I can see it in ETO Terms Form and settings work.

**Technical notes**

**Testing notes**

**Comment by pstroinski** [comment] 2020-01-31 09:54
Duplicate of currently implemented https://github.com/Neufund/platform-frontend/issues/3963

**Closed by pstroinski** 2020-01-31 09:54 UTC
Labels: Outdated!
