### ISSUE TITLE
[E2E] [KYC] Individual verification with IDnow 

### ISSUE THREAD

**Issue by krzkaczor** [Neufund/platform-frontend#753] opened 2018-05-18 09:27 UTC
Use special api provided by backend team to control verification status. Test things like failed verification as well.

**Comment by Moejoe90** [comment] 2019-01-22 10:59
Blocked by https://github.com/Neufund/platform-backend/issues/1320

**Comment by desfero** [comment] 2019-12-06 14:12
Duplicate of #3818

**Closed by desfero** 2019-12-06 14:12 UTC
Labels: Blocked, E2E test
