### ISSUE TITLE
Provacy policy on platform.neufund.org

### ISSUE THREAD

**Issue by vizmab** [Neufund/platform-frontend#3254] opened 2019-08-01 10:16 UTC
**Background**
Currently, the Privacy Policy on this page https://platform.neufund.org/ links to an outdated PDF document. It should link to https://neufund.org/privacy-policy.
**Designs**
Just a link
**Acceptance criteria**
Privacy policy on this page https://platform.neufund.org/ links to https://neufund.org/privacy-policy.
**Technical notes**
-
**Testing notes**

**Comment by andywalton** [comment] 2019-08-01 10:19
Hey Panor, please will you factor this ticket in.

**Comment by pstroinski** [comment] 2019-08-07 14:15
Duplicate of @3282

**Closed by pstroinski** 2019-08-07 14:15 UTC
