### ISSUE TITLE
Upgrade Formik to latest

### ISSUE THREAD

**Issue by Moejoe90** [Neufund/platform-frontend#1574] opened 2018-10-16 14:25 UTC
**Background** 
Lots of bugs are fixed between version `1.2` and `1.3.1` so it's about time to push the forms forward.
https://github.com/jaredpalmer/formik/releases

**Tasks**
Upgrade Formik, Then make sure that all the forms are not affected this should be relatively easy in the sense by using `KYC` and `ETO issuer` E2E tests as a guide

Add initial validation to some forms: https://github.com/Neufund/platform-frontend/pull/3711/files#diff-827f83fde4da5cba1c2adcea685da895R45.

**Comment by desfero** [comment] 2018-12-23 09:46
Trying to update formik still breaks our forms that use `componentDidMount` to set default values. Related formik issues seems to be not fixed yet https://github.com/jaredpalmer/formik/issues/930

**Comment by desfero** [comment] 2018-12-23 09:49
Postponed until bug is fixed or new release (Formik 2.0) released

**Comment by pstroinski** [comment] 2019-06-04 08:39
v2 is getting close. We should implement when it's released

**Comment by glupiawymowka** [comment] 2020-03-03 16:45
- [ ] if the image in any of the `Pitch` form inputs is left or right-aligned, it crosses the area of the other fields: 

![image](https://user-images.githubusercontent.com/18315589/75798155-73e2f800-5d76-11ea-842c-256cfe179da1.png)

- [ ] negative values added in `Legal info` forms are disappearing without notice. 
It is good that we don't accept them, but we should have an error message. 
You can reproduce by opening the mentioned form, adding a negative value and moving to another input

**Comment by glupiawymowka** [comment] 2020-03-04 10:49
we agreed that the issues discovered are being moved to a separate ticket as they are non-blocking. 
Thus, this one is considered as tested on stage

**Closed** 2020-03-04 18:46 UTC
Labels: QA approved, Sprint, TECH
