### ISSUE TITLE
Small fixes. Investor dashboard. 

### ISSUE THREAD

**Issue by SergejSoft** [Neufund/platform-frontend#1390] opened 2018-09-21 10:02 UTC
Small fix

- when I clicked "invest entire wallet balance" I got an error saying "sorry this amount exceeds your wallet balance" - pls. try to fix. this.

**Comment by desfero** [comment] 2018-10-08 12:40
```
remove underlines from all links (confirm with Kirstyn but this looks ugly IMO) example: side nav, eto opportunities on dashboard, etc.
```
is already on master

**Comment by trival** [comment] 2018-10-08 13:46
> When you click invest now under ETO opportunties on dashboard, ICBM wallet shows up twice as an option. Pls. check if that is the case. Was not able to open this with metamask.

That is correct, there is one icbm wallet for ether, and on for neuro

**Comment by rudolfix** [comment] 2018-10-21 18:19
duplicate of set of more concrete bugs

**Closed by rudolfix** 2018-10-21 18:19 UTC
