### ISSUE TITLE
Removing KYC field from frontend related to isHighIncome - impact on claims registry

### ISSUE THREAD

**Issue by andywalton** [Neufund/platform-frontend#3515] opened 2019-09-24 13:13 UTC
**Background**
There is a frontend ticket to remove a field from our KYC for individual investors. #2825 

This field is:
**Is your income above 5k or do you have more than 10k EUR of assets available?**

@drakkein is busy with this ticket and the backend is throwing an error without `isHighIncome` present inside KYC data. We can't set a default of `true` or `false` for this and the proposal is to set it as `undefined`.

[Read the Slack thread](https://neufund.slack.com/archives/GAK8XK0CB/p1569323446004100)

I just spoke to Dialika about this and she says `undefined` is fine. This question was only related to the case of an ETO offering that is a German Investment Asset (in other words, a non-transferable German investment asset that had some restrictions regarding how much each investor could invest). Something we aren’t really promoting.

If in future we have such an offering on the platform, we could then handle this as part of the investment flow on a per investor basis and ask the question before they can invest. Ie. because of this type of offering, we need to know if you income is higher or lower than x due to regulatory reasons etc. (better language obviously). The investor would then set this field and we’d then need to update the onchain registry for that investor with `isHighIncome` set to something other than `undefined`.

I therefore don’t think we should completely remove this field from the backend until we decide to not offer this German Investment Asset ETO product. We however do need hide this from KYC and make it not required.

@rudolfix - you mentioned that this in fact a deeper change in how the claims registry works and we should look at this from a backend point of view.

I'd say then we should allow us to default this value to `undefined` and figure out the claims registry piece.

_Tasks and how this ticket should be broken up - please do that here._

**Comment by pstroinski** [comment] 2019-09-24 14:45
Duplicate of #2147 (backend)

**Closed by pstroinski** 2019-09-24 14:45 UTC
